---
- name: Include vesxi vars
  include_vars: vesxi_vars.yml
  tags: ["deploy_vesxi"]

- name: Generate list for number of hosts
  set_fact:
    mysequence: "{{ range(1, vesxi_host_count + 1) | list }}"
  tags: ["deploy_vesxi"]

- name: deploy vesxi
  include_tasks: vesxi_loop.yml
  loop: "{{ mysequence }}"
  loop_control:
    extended: yes
    loop_var: outer_item
  tags: ["deploy_vesxi"]