---
- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true
  delegate_to: localhost
  tags: ["always","golang"]

- name: Set GOPATH
  set_fact:
    go_path: "{{ ansible_env.HOME }}/go/"
    go_bin: "/home/homelab/go/bin/"
  delegate_to: localhost
  tags: ["always", "golang"]

- name: debug task to print out paths set above
  debug:
    msg:
    - "GOPATH is {{ go_path }}"
    - "PATH is {{ go_bin }}"
  tags: ["golang"]

- name: govc test
  connection: local
  shell: govc version
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
  register: govc_result
  tags: ["golang"] 

- debug:
    msg: "{{ govc_result }}"
  tags: ["golang"]

- name: debug variable
  debug:
    msg: "{{ ansible_env.HOME }}"
  tags: ["golang"]