---
- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true
  delegate_to: localhost
  tags: ["always","golang"]

- name: Set GOPATH
  set_fact:
    go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"
    go_bin: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go/bin/', true) }}"
  delegate_to: localhost
  tags: ["always", "golang"]

- name: debug task to print out paths set above
  debug:
    msg:
    - "GOPATH is {{ go_path }}"
    - "PATH is {{ go_bin }}"
  tags: ["golang"]
