---
#- name: Add PiMaster DNS Server
#  command: esxcli network ip dns server add -s 192.168.1.44
#  when: fresh | default(False)
#  tags: ['dns']

#- name: Remove default entry added during install
#  command: esxcli network ip dns server remove -s 192.168.1.1
#  when: fresh | default(False)
#  tags: ['dns']

- name: Get vSwitch list to decide which ones need creating
  shell: esxcli --formatter=csv --format-param=fields="Name" network vswitch standard list | awk 'NR > 1' | sed 's/,//'
  register: vswitch_raw
  changed_when: false
  check_mode: false
  tags: ['vswitch']

- debug:
    msg: "{{ vswitch_raw }}"
    verbosity: 2
  tags: ['vswitch']

- name: convert list to var
  set_fact:
    vswitches: "{{ vswitch_raw.stdout_lines }}"
  tags: ['vswitch']

- debug:
    msg: "{{ vswitches }}"
    verbosity: 2
  tags: ['vswitch']

- name: Get list of existing portgroups to decided which ones need creating
  shell: "esxcli --formatter=csv --format-param=fields=\"Name\" network vswitch standard portgroup list | awk 'NR > 1' | sed 's/,//'"
  register: portgroup_raw
  changed_when: false
  check_mode: false
  tags: ['vswitch']

- name: Convert portgroup list to var
  set_fact:
    portgroups: "{{ portgroup_raw.stdout_lines }}"
  tags: ['vswitch']

- debug:
    msg: "{{ portgroup_raw }}"
    verbosity: 2
  tags: ['vswitch']

- debug:
    msg: "{{ portgroups }}"
    verbosity: 2
  tags: ['vswitch']

- name: Create missing vswitches
  command: "esxcli network vswitch standard add --vswitch-name {{ item.key }}"
  with_dict: "{{ network_vars }}"
  when: item.key not in vswitches
  tags: ['vswitch']

- name: Create missing portgroups
  command: "esxcli network vswitch standard portgroup add --portgroup-name {{ item.portgroup_name }} --vswitch-name {{ item.vswitchName }}"
  with_items: "{{ pg_vars }}"
  when: item.value.portgroup_name not in portgroups
  tags: ['vswitch']

- name: Set default portgroup
  set_fact:
    default_portgroup: "{{ item.value.portgroup_name }}"
  with_dict: "{{ pg__vars }}"
  when: item.value.default|bool == true
  tags: ['vswitch']
#- name: Create vSwitch - LabMgmt
#  command: "esxcli network vswitch standard add --vswitch-name {{ item.vswitch_name }}"
#  with_items: "{{ network_vars }}"
#  when: fresh | default(False)
#  tags: ['vswitch']

#- name: Create Port Group
#  command: "esxcli network vswitch standard portgroup add --portgroup-name {{ item.portgroup_name }} --vswitch-name {{ item.vswitch_name }}"
#  with_items: "{{ network_vars }}"
#  when: fresh | default(False)
#  tags: ['vswitch']