---
#- name: Add PiMaster DNS Server
#  command: esxcli network ip dns server add -s 192.168.1.44
#  when: fresh | default(False)
#  tags: ['dns']

#- name: Remove default entry added during install
#  command: esxcli network ip dns server remove -s 192.168.1.1
#  when: fresh | default(False)
#  tags: ['dns']

- name: Get vSwitch list to decide which ones need creating
  shell: esxcli --formatter=csv --format-param=fields="Name" network vswitch standard list | awk 'NR > 1' | sed 's/,//'
  register: vswitch_raw
  changed_when: false
  check_mode: false
  tags: ['vswitch']

- debug:
    msg: "{{ vswitch_raw }}"
  tags: ['vswitch']

- name: convert list to var
  set_fact:
    vswitches: "{{ vswitch_raw.stdout_lines }}"
  tags: ['vswitch']

- debug:
    msg: "{{ vswitches }}"
  tags: ['vswitch']

- name: Create missing vswitches
  command: "esxcli network vswitch standard add --vswitch-name {{ item.vswitch_name }}"
  with_items: "{{ network_vars }}"
  when: item.vswitch_name not in vswitches
  tags: ['vswitch']
#- name: Create vSwitch - LabMgmt
#  command: "esxcli network vswitch standard add --vswitch-name {{ item.vswitch_name }}"
#  with_items: "{{ network_vars }}"
#  when: fresh | default(False)
#  tags: ['vswitch']

#- name: Create Port Group
#  command: "esxcli network vswitch standard portgroup add --portgroup-name {{ item.portgroup_name }} --vswitch-name {{ item.vswitch_name }}"
#  with_items: "{{ network_vars }}"
#  when: fresh | default(False)
#  tags: ['vswitch']