---
#- name: Check existing NFS mounts
- name: import vars for nfs
  include_vars: nfs-  vars.yml
  tags: ['nfs']

- name: Get NFS volume list to decide which ones need creating
  shell: esxcli --formatter=csv --format-param=fields="Volume Name" storage nfs list | awk 'NR > 1' | sed 's/,//'
  register: nfs_csv
  changed_when: false
  check_mode: false
  tags: ['nfs']

- name: convert nfs_csv to var
  set_fact:
    nfs_mounts: "{{ nfs_csv.stdout_lines }}"
  tags: ['nfs']

- debug:
   msg: "{{ nfs_mounts }}"
  tags: ['nfs']

#Mount the NFS share from pimaster
- name: Mount NFS
  shell: esxcli storage nfs add --host={{ hostvars['pimaster'].ansible_host }} --share={{ nfs_share_path }} --volume-name={{ nfs_mount_name }}
  tags: ['nfs']
  when: nfs_mount_name not in nfs_mounts

#- include: create_nfs.yml
#  when: 

#Get vmfs extents
#if 1 - set_fact of name for vm install
#if not > 0
#find first disk
#partition it and vmfs it