---
#- name: Check existing NFS mounts
- name: import vars for nfs
  include_vars: nfs-vars.yml
  tags: ["nfs"]

- name: Get NFS volume list to decide which ones need creating
  shell: esxcli --formatter=csv --format-param=fields="Volume Name" storage nfs list | awk 'NR > 1' | sed 's/,//'
  register: nfs_csv
  changed_when: false
  check_mode: false
  tags: ["nfs"]

- name: convert nfs_csv to var
  set_fact:
    nfs_mounts: "{{ nfs_csv.stdout_lines }}"
  tags: ["nfs"]

- name: debug for nfs
  debug:
    msg: "{{ nfs_mounts }}"
  tags: ["nfs"]

#Mount the NFS share from pimaster
- name: Mount NFS
  shell: esxcli storage nfs add --host={{ hostvars['pimaster'].ansible_host }} --share={{ nfs_share_path }} --volume-name={{ nfs_mount_name }}
  tags: ["nfs"]
  when: nfs_mount_name not in nfs_mounts

#VMFS Datastores
- name: Get VMFS volume list to decide which ones need creating
  shell: esxcli storage filesystem list > /tmp/filesystem.csv
  tags: ["vmfs"]

- name: Read filesystems from CSV file and return a dictionary
  read_csv:
    path: /tmp/filesystem.csv
    key: "Volume Name"
  register: vmfs_mounts
  tags: ["vmfs"]

- name: debug for vmfs
  debug:
    msg: "{{ vmfs_mounts }}"
  tags: ["vmfs"]
#Get vmfs extents
#if 1 - set_fact of name for vm install
#if not > 0
#find first disk
#partition it and vmfs it
  #shell: esxcli --formatter=csv --format-param=fields="Volume Name,Mounted,Type,Size,Free" storage filesystem list