---
#- name: Check existing NFS mounts
  
- name: Get NFS volume list to decide which ones need creating
  shell: esxcli --formatter=csv --format-param=fields="Volume Name" storage nfs list
  register: nfs_json
  changed_when: false
  check_mode: false
  tags: ['nfs']

- name: convert nfs_json to var
  set_fact:
    nfs_mounts: "{{ nfs_json.stdout }}"
  tags: ['nfs']

- debug:
   msg: "{{ nfs_mounts }}"
  tags: ['nfs']

- debug: 
    msg: "{{ ('nfs_mounts.VolumeName') }}"
  tags: ['nfs']
#- include: create_nfs.yml
#  when: 

#Get vmfs extents
#if 1 - set_fact of name for vm install
#if not > 0
#find first disk
#partition it and vmfs it

