---
- name: Debug count
  debug:
    msg: "{{ outer_item }}"
  tags: ["deploy_vesxi"]

- name: Debug loop index
  debug:
    msg: "{{ ansible_loop.index }}"
  tags: ["deploy_vesxi"]

- name: template out deploy.json
  template:
    src: vesxi.json.j2
    dest: vesxi{{ outer_item.ansible_loop.index }}.json
  delegate_to: localhost
  tags: ["deploy_vesxi"]  
#- name: Copy using inline content to second file
# # copy:
#  #  content: |
#   #   ip_address={{ item }}
#    #dest: /etc/some_other_config_file.conf