---
- name: Debug count
  debug:
    msg: "{{ outer_item }}"
    verbosity: 2
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Debug loop index
  debug:
    msg: "{{ ansible_loop.index }}"
    verbosity: 2
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: template out deploy.json
  template:
    src: vesxi.json.j2
    dest: vesxi{{ outer_item }}.json
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: IP to check
  set_fact:
    current_ip: "{{ vesxi_starting_ip|ipmath(ansible_loop.index0) }}"
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: VM name to check
  set_fact:
    current_name: "{{ vesxi_basename }}{{ ansible_loop.index}}"
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Debug current_ip
  debug:
    msg: "{{ current_ip }}"
    verbosity: 3
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Debug ip_results
  debug:
    msg: "{{ ip_results }}"
    verbosity: 3
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Debug current_name
  debug:
    msg: "{{ current_name }}"
    verbosity: 2
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Debug current_vms
  debug:
    msg: "{{ current_vms }}"
    verbosity: 2
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Deploy vesxi{{ outer_item }}
  shell: govc library.deploy -dc={{ vcsa_dc_name }} /{{ content_library_name }}/{{ vesxi_ovf_name }} {{ vesxi_basename }}{{ ansible_loop.index}} -options vesxi{{ outer_item }}.json
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
    GOVC_INSECURE: 1
    GOVC_URL: "{{ vcsa_dns_name }}"
    GOVC_USERNAME: "{{ vcsa_username }}@{{ vcsa_sso_domain }}"
    GOVC_PASSWORD: "{{ esx_password }}"
    GOVC_RESOURCE_POOL: "*/Resources"
  when: current_name not in current_vms
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: Check powerstate of vesxi{{ outer_item }}
  shell: govc vm.info -json vesxi{{ outer_item }} | /usr/bin/jq .VirtualMachines[].Runtime.PowerState
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
    GOVC_INSECURE: 1
    GOVC_URL: "{{ vcsa_dns_name }}"
    GOVC_USERNAME: "{{ vcsa_username }}@{{ vcsa_sso_domain }}"
    GOVC_PASSWORD: "{{ esx_password }}"
    GOVC_RESOURCE_POOL: "*/Resources"
  delegate_to: localhost
  register: vm_powerstate
  tags: ["deploy_vesxi"]

- name: Debug vm powerstate
  debug:
    var: "{{ vm_powerstate.stdout }}"
    #verbosity: 2
  delegate_to: localhost
  tags: ["deploy_vesxi"]

- name: PowerOn  vesxi{{ outer_item }}
  shell: govc vm.power -on {{ vesxi_basename }}{{ ansible_loop.index}}
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
    GOVC_INSECURE: 1
    GOVC_URL: "{{ vcsa_dns_name }}"
    GOVC_USERNAME: "{{ vcsa_username }}@{{ vcsa_sso_domain }}"
    GOVC_PASSWORD: "{{ esx_password }}"
    GOVC_RESOURCE_POOL: "*/Resources"
  delegate_to: localhost
  when: vm_powerstate.stdout != "poweredOn"
  tags: ["deploy_vesxi"]
#not in ip_results


#- name: Copy using inline content to second file
# # copy:
#  #  content: |
#   #   ip_address={{ item }}
#    #dest: /etc/some_other_config_file.conf