---

- name: Get device list to decide which one to use
  shell: esxcli --formatter=csv --format-param=fields="Device,DisplayName,Size,DevfsPath,Status,IsLocal,IsSSD,IsUSB,IsBootDevice" storage core device list > /tmp/devices.csv
  tags: ["new_vmfs", "vmfs"]

- name: Read CSV
  read_csv:
    path: /tmp/devices.csv
    key: Device
  register: phy_disks
  tags: ["new_vmfs", "vmfs"]

#- name: debug for vmfs
#  debug:
#    msg: "{{ phy_disks }}"
#  tags: ["new_vmfs", "vmfs"]

- name: Print dictionary
  debug:
    msg: "{{ item.key }}: {{ item.value }}"
  loop: "{{ lookup('dict', phy_disks.dict)}}"
  tags: ["new_vmfs", "vmfs"]

- name: Get disk
  set_fact:
    physical_disk_id: "{{ item.key }}"
  loop: "{{ lookup('dict', phy_disks.dict) }}"
  when: item.value.IsBootDevice is "true"
  tags: ["new_vmfs", "vmfs"]

- name: Debug selected disk
  debug:
    msg: "{{ physical_disk_id }}"
  tags: ["new_vmfs", "vmfs"]
#Get vmfs extents
#if 1 - set_fact of name for vm install
#if not > 0
#find first disk
#partition it and vmfs it
  #shell: esxcli --formatter=csv --format-param=fields="Volume Name,Mounted,Type,Size,Free" storage filesystem list