---
- name: Include secrets
  include_vars: 
    file: secrets_physical_esx.yml
  tags: ["vms"]

- name: import vars for nfs
  include_vars: nfs-vars.yml
  tags: ["vms"]

- name: Hacky fix for VM creation - generate guid
  shell: dbus-uuidgen | cut -c 1-12
  register: guid
  delegate_to: localhost
  tags: ["vms"]
  
- name: deploy dummy vm (Hacky fix)
  shell: govc vm.create {{ guid.stdout }}
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
    GOVC_INSECURE: 1
    GOVC_URL: "{{ esx_address }}"
    GOVC_USERNAME: "{{ esx_user }}"
    GOVC_PASSWORD: "{{ esx_password }}"
    GOVC_DATASTORE: "{{ default_datastore }}"
    GOVC_NETWORK: "{{ default_portgroup }}"
    GOVC_RESOURCE_POOL: "*/Resources"
  delegate_to: localhost
  tags: ["vms"]

- name: Get VMs
  shell: esxcli --formatter=csv vm process list > /tmp/vms.csv
  tags: ["pre_vms", "vms"]

- name: stat file to check it is not zero
  shell: wc -c /tmp/vms.csv  | awk '{print $1}'
  register: stvm
  tags: ["vms"]

- name: Read CSV
  read_csv:
    path: /tmp/vms.csv
    key: DisplayName
  register: vms
  when: stvm.stdout != "0"
  tags: ["pre_vms", "vms"]

- name: Debug to show VMs
  debug:
    msg: "{{ vms }}"
    verbosity: 2
  tags: ["pre_vms", "vms"]

- name: Include pfsense vars
  include_vars: pfsense_vars.yml
  tags: ["pfsense"]

- name: Deploy pfsense OVF
  command: "{{ pfsense_ovftool_path }} --acceptAllEulas --noSSLVerify --name={{ pfsense_vm_name }} --X:logFile=/vmfs/volumes/{{ nfs_mount_name }}/ovftool.log -dm={{ pfsense_provision_mode }} -ds={{ default_datastore }} --powerOn {{ pfsense_ovf_path }} \"vi://{{ esx_user }}:{{ esx_password }}@{{ esx_address }}\""
  tags: ["pfsense"]

- name: Include vcsa vars
  include_vars: vcsa_vars.yml
  tags: ["vcsa_deploy"]

- name: deploy VCSA
  shell: govc import.ova -options=vcsa3.json /mnt/usb/vcsa_iso/vcsa/VMware-vCenter-Server-Appliance-6.7.0.40000-14367737_OVF10.ova 
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
    GOVC_INSECURE: 1
    GOVC_URL: "{{ esx_address }}"
    GOVC_USERNAME: "{{ esx_user }}"
    GOVC_PASSWORD: "{{ esx_password }}"
    GOVC_DATASTORE: "{{ default_datastore }}"
    GOVC_NETWORK: "{{ default_portgroup }}"
    GOVC_RESOURCE_POOL: "*/Resources"
  async: 3600
  poll: 5
  delegate_to: localhost
  tags: ["vcsa_deploy"]

- name: Wait for ping  to VCSA
  command: /bin/ping -c 1 {{ vcsa_ip_addr }}
  register: result
  retries: 150
  delay: 10
  until: result is not failed
  delegate_to: localhost
  tags: ["vcsa_deploy"]

- name: Pause play until a URL is reachable from this host
  uri:
    url: "http://{{ vcsa_ip_addr }}/ui"
    follow_redirects: all
    method: GET
    validate_certs: no
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds
  delegate_to: localhost
  tags: ["vcsa_deploy"]
  
- name: Remove dummy vm (END Hacky fix)
  shell: govc vm.destroy {{ guid.stdout }}
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_bin }}"
    GOVC_INSECURE: 1
    GOVC_URL: "{{ esx_address }}"
    GOVC_USERNAME: "{{ esx_user }}"
    GOVC_PASSWORD: "{{ esx_password }}"
    GOVC_DATASTORE: "{{ default_datastore }}"
    GOVC_NETWORK: "{{ default_portgroup }}"
    GOVC_RESOURCE_POOL: "*/Resources"
  delegate_to: localhost
  tags: ["vms"]
#- name: Include pfsense VM tasks
#  include_tasks: pfsense.yml
#  when: stvm.stdout == "0"
#  tags: ["pfsense", "vms"]
# date | sed '/^$/d;s/[[:blank:]]//g'