---
- name: Include secrets
  include_vars: 
    file: secrets_physical_esx.yml
    name: physical_esx

- name: Deploy pfsense OVF
  command: "{{ item.ovftool_path }} --acceptAllEulas --noSSLVerify --name={{ item.vm_name }} -dm={{ item.provision_mode }} -ds={{ item.datastore }} {{ item.ovf_path }} \"vi://{{ physical_esx.esx_user }}:{{ physical_esx.esx_password }}@{{ physical_esx.esx_address }}\""
  with_items: "{{ pfsense_vars }}"
  tags: ["pfsense"]

#- name: Enable autostart
#- name: Deploy VCSA