---
- name: Include secrets
  include_vars: 
    file: secrets_physical_esx.yml
  tags: ["vms"]

- name: import vars for nfs
  include_vars: nfs-vars.yml
  tags: ["vms"]

- name: Get VMs
  shell: esxcli --formatter=csv vm process list > /tmp/vms.csv
  tags: ["pre_vms", "vms"]

- name: stat file to check it is not zero
  shell: wc -c /tmp/vms.csv  | awk '{print $1}'
  register: stvm
  tags: ["vms"]

- name: Read CSV
  read_csv:
    path: /tmp/vms.csv
    key: DisplayName
  register: vms
  when: stvm.stdout != "0"
  tags: ["pre_vms", "vms"]

- name: Debug to show VMs
  debug:
    msg: "{{ vms }}"
    verbosity: 2
  tags: ["pre_vms", "vms"]

- name: Include pfsense vars
  include_tasks: pfsense.yml
  when: vms is undefined
  tags: ["pfsense", "vms"]