---
pg_vars:
  - {vswitchName: vswitch_LabMgmt,
      portgroup_name: pg_LabMgmt,
      default: True,
      vlan: 100}
  - {vswitchName: vswitch_LabMgmt,
      portgroup_name: Nested_ESXi,
      default: False,
      vlan: 4095}

vswitch_vars:
  - {vswitchName: vswitch_LabMgmt,
      allow_forged_transmits: True,
      allow_mac_change: True,
      allow_promiscuous: True}

pfsense_vars:
 - vm_name: pfsense
   wan_pg: "VM Network"
   wan_ip: 192.168.1.12
   lan_pg: pg_LabMgmt
   lan_ip: 10.64.0.1
   provision_mode: thin
   ovftool_path: /vmfs/volumes/{{ default_nfs }}/vmware-ovftool/ovftool
   ovf_path: /vmfs/volumes/{{ default_nfs }}/pfsense.ovf
